name: inject
version: 1.0.1-alpha
description: Compile-time dependency injection for Dart

homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.1.2
