name: inject_generator
version: 1.0.1-alpha
description: Dev-time dependency for package:inject.

homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.15.0-nullsafety.4
  dart_style: ^2.2.4
  logging: ^1.1.0
  meta: ^1.1.2
  path: ^1.5.1
  quiver: ^3.1.0
  stack_trace: ^1.9.2

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  inject:
    version: ^1.0.1-alpha
    path: ../inject
  test: ^1.5.0
