name: inject.example.train
description: A more complex example of using package:inject

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  inject:
    version: ^1.0.1-alpha
    path: ../../package/inject

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  build_web_compilers: ^3.2.7
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.0.0
